# -----------------------------------------------------------------------------
# @author    Auto-generated by STM32CubeIDE for Visual Studio Code Extension
# -----------------------------------------------------------------------------
# @attention
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.
#
# -----------------------------------------------------------------------------

# This is converter generated file, and shall not be touched by user
#
# Use CMakeLists.txt to apply user changes
cmake_minimum_required(VERSION 3.20)

# Core MCU flags, CPU, instruction set and FPU setup
set(cpu_PARAMS ${cpu_PARAMS} ${CPU_FLAGS})

# Linker script
set(linker_script_SRC ${linker_script_SRC}
	${CMAKE_CURRENT_SOURCE_DIR}/stm32f303x8_flash.ld
)

# Sources
set(sources_SRCS ${sources_SRCS}
	${CMAKE_CURRENT_SOURCE_DIR}/Src/syscall.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/sysmem.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/startup_stm32f303xx.S
)

# Include directories
set(include_c_DIRS ${include_c_DIRS}
)
set(include_cxx_DIRS ${include_cxx_DIRS}
)
set(include_asm_DIRS ${include_asm_DIRS}
)

# Symbols definition
set(symbols_c_SYMB ${symbols_c_SYMB}
	RTE_DEVICE_STARTUP_STM32F3XX
)
set(symbols_cxx_SYMB ${symbols_cxx_SYMB}
)
set(symbols_asm_SYMB ${symbols_asm_SYMB}
)

# Link directories
set(link_DIRS ${link_DIRS}
)

# Link libraries
set(link_LIBS ${link_LIBS}
)

# Compiler options
set(compiler_OPTS ${compiler_OPTS})

# Linker options
set(linker_OPTS ${linker_OPTS})
